services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  stock_service:
    build: ./stock_service
    ports:
      - "5002:5002"
    environment:
      KAFKA_SERVER: kafka:9092
    depends_on:
      - kafka
      
  order_service:
    build: ./order_service
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - user_service
      - stock_service
      - payment_service
      - notification_service
    environment:
      KAFKA_SERVER: kafka:9092
      
  payment_service:
    build: ./payment_service
    ports:
      - "5003:5003"
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: kafka:9092

  notification_service:
    build: ./notification_service
    ports:
      - "5004:5004"
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: kafka:9092

  user_service:
    build: ./user_service
    ports:
      - "5005:5005"
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: kafka:9092
  api_gateway:
    build: ./api_gateway
    ports:
      - "5000:5000"
    depends_on:
      - order_service
      - payment_service
      - stock_service
      - notification_service